# Generated by Django 5.1.4 on 2025-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Yazının kısa özeti', verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/%Y/%m/', verbose_name='Öne Çıkan Görsel'),
        ),
    ]
